sonar.projectKey=cism-learnlink_backend
sonar.organization=cism-learnlink
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=**/node_modules/**,tests/**,uploads/**,public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
